In [399]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from keras.models import Sequential
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
import numpy as np
import cv2

In [400]:
train_df = pd.read_csv("fer2013.csv")
test_df = pd.read_csv("test.csv")

In [401]:
X_train = train_df[train_df["Usage"] == "Training"]
y_train = X_train.drop(["pixels", "Usage"], axis=1)
X_test = train_df[train_df["Usage"] == "PublicTest"]
y_test = X_test.drop(["pixels", "Usage"], axis=1)

In [402]:
X_train = X_train.drop(["Usage", "emotion"], axis=1)
X_test = X_test.drop(["Usage", "emotion"], axis=1)

In [403]:
my_list = X_train["pixels"].to_list()
my_list_1 = X_test["pixels"].to_list()
y_train = y_train["emotion"].to_numpy()
y_test = y_test["emotion"].to_numpy()

In [404]:
width, height = 48, 48
input_shape = (48, 48, 1)

In [405]:
def convert_to_np(my_list):
    faces = []
    for i in my_list:
        face = np.asarray(i.split(" "), dtype=np.uint8).reshape(width, height)
        face = cv2.resize(face.astype('uint8'), (width, height))
        faces.append(face.astype('float32'))
        
    faces = np.asarray(faces)
    faces = np.expand_dims(faces, -1)
    
    return faces

In [406]:
X_train = convert_to_np(my_list)
X_test = convert_to_np(my_list_1)
#y_train = np.asarray(y_train)
#y_test = np.asarray(y_test)

In [407]:
X_train /= 255.
X_test /= 255.

In [408]:
y_train

array([0, 0, 2, ..., 4, 0, 4], dtype=int64)

In [409]:
CLASSES = 7

In [410]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation="relu", input_shape=input_shape))
model.add(MaxPooling2D())
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(64, activation="relu"))
model.add(Dense(CLASSES, activation='softmax'))

In [411]:
model.compile(loss='sparse_categorical_crossentropy',
                            optimizer='adam', metrics=['accuracy'])

In [412]:
X_train

array([[[[0.27450982],
         [0.3137255 ],
         [0.32156864],
         ...,
         [0.20392157],
         [0.16862746],
         [0.16078432]],

        [[0.25490198],
         [0.23921569],
         [0.22745098],
         ...,
         [0.21960784],
         [0.20392157],
         [0.17254902]],

        [[0.19607843],
         [0.16862746],
         [0.21176471],
         ...,
         [0.19215687],
         [0.21960784],
         [0.18431373]],

        ...,

        [[0.35686275],
         [0.25490198],
         [0.16470589],
         ...,
         [0.28235295],
         [0.21960784],
         [0.16862746]],

        [[0.3019608 ],
         [0.32156864],
         [0.30980393],
         ...,
         [0.4117647 ],
         [0.27450982],
         [0.18039216]],

        [[0.3019608 ],
         [0.28235295],
         [0.32941177],
         ...,
         [0.41568628],
         [0.42745098],
         [0.32156864]]],


       [[[0.5921569 ],
         [0.5882353 ],
         [0.57

In [413]:
model.fit(X_train, y_train,
                        validation_data=(X_test, y_test),
                        epochs=5, batch_size=32, verbose=1)

Epoch 1/5
898/898 [==============================] - 4s 4ms/step - loss: 1.6260 - accuracy: 0.3613 - val_loss: 1.4885 - val_accuracy: 0.4316
Epoch 2/5
898/898 [==============================] - 4s 4ms/step - loss: 1.4270 - accuracy: 0.4497 - val_loss: 1.3742 - val_accuracy: 0.46420.
Epoch 3/5
898/898 [==============================] - 4s 4ms/step - loss: 1.3047 - accuracy: 0.5013 - val_loss: 1.3586 - val_accuracy: 0.4700
Epoch 4/5
898/898 [==============================] - 4s 4ms/step - loss: 1.2014 - accuracy: 0.5451 - val_loss: 1.3296 - val_accuracy: 0.4923
Epoch 5/5
898/898 [==============================] - 4s 4ms/step - loss: 1.1020 - accuracy: 0.5878 - val_loss: 1.3153 - val_accuracy: 0.5024


In [414]:
X_test

array([[[[0.99607843],
         [0.99607843],
         [0.99607843],
         ...,
         [0.0627451 ],
         [0.        ],
         [0.6313726 ]],

        [[0.99607843],
         [0.99607843],
         [0.99607843],
         ...,
         [0.06666667],
         [0.        ],
         [0.47843137]],

        [[0.99607843],
         [0.99607843],
         [0.99607843],
         ...,
         [0.10196079],
         [0.        ],
         [0.44705883]],

        ...,

        [[0.25882354],
         [0.3372549 ],
         [0.3882353 ],
         ...,
         [1.        ],
         [0.9882353 ],
         [0.99607843]],

        [[0.32941177],
         [0.36078432],
         [0.36078432],
         ...,
         [0.9254902 ],
         [1.        ],
         [1.        ]],

        [[0.3647059 ],
         [0.3529412 ],
         [0.33333334],
         ...,
         [0.16470589],
         [0.5058824 ],
         [0.7058824 ]]],


       [[[0.6117647 ],
         [0.72156864],
         [0.77

In [415]:
model.predict(X_test)

array([[6.2931675e-01, 3.7110534e-03, 2.5452274e-01, ..., 7.6454215e-02,
        7.8989612e-04, 2.1618968e-02],
       [1.3173616e-01, 2.1760793e-01, 1.8605350e-01, ..., 1.4113624e-01,
        1.8870777e-01, 5.3002782e-02],
       [1.7039916e-01, 1.5038698e-02, 3.0539596e-01, ..., 2.1241905e-01,
        1.2376572e-02, 2.7985024e-01],
       ...,
       [4.4726059e-02, 4.3347004e-04, 2.0167163e-02, ..., 2.2505362e-01,
        6.4234376e-02, 2.6519313e-01],
       [4.4927531e-01, 1.8330444e-02, 2.1355861e-01, ..., 2.5682202e-01,
        4.8451166e-04, 6.1262861e-02],
       [2.5372727e-02, 1.3997762e-03, 2.6186168e-01, ..., 1.0939094e-01,
        1.2034500e-01, 4.7258407e-01]], dtype=float32)

In [416]:
model.save("emotion.h5")